---
title: "Day 2 Tasks"
author: "Grace Lewin"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```


## First order univariate derivatives:

### A)
```{r}
fx <- expression(x^2)

df_dx = D(expr = fx, 'x')
df_dx

x = 3
eval(expr = df_dx)
```

### B)
```{r}
Pa <- expression(2 * ((3*a + 2)^4) - 5)

dP_da = D(expr = Pa, 'a')
dP_da

a = 1.2
eval(expr = dP_da)
```

### C)
```{r}
gt <- expression((-4*t)/(((t^2) + 1)^3))

dg_dt = D(expr = gt, 't')
dg_dt

t = 0
eval(dg_dt)
```

## Higher Order univariate derivatives

```{r}
Gz <- expression(4.6 - 1.9 * z^3)

dG_dt = D(expr = Gz, 'z')

d2G_dt2 = D(expr = dG_dt, 'z')
d2G_dt2
```

## Partial Derivatives

```{r}
f_xyz <- expression((2 * x^2 * y) - (3 * x) + 1 + (4*z^4*x))

df_dx_ = D(expr = f_xyz, 'x')
df_dx_

df_dy = D(expr = f_xyz, 'y')
df_dy


df_dz = D(expr = f_xyz, 'z')
df_dz
```

# Section 4: Make some plots

```{r}

eq <- function(x) {
  
  2.4 * (exp(-0.05*x))*sin(x)
  
}

ggplot(data = data.frame(x = c(-0.5, 0.5)), aes(x = x)) +
  stat_function(fun = eq)
```


```{r}
ggplot(data = penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + 
  geom_point(aes(color = species)) +
  labs(x = "Bill Depth (mm)", 
       y = "Bill Length (mm)",
       title = "Palmer penguins bill length vs. bill depth")
```


```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  labs(x = "Species", 
       y = "Flipper Length (mm)",
       title = "Palmer penguins flipper length by species")
```


